/* eslint-disable */
// Generated by Wrangler by running `wrangler types assistant-worker/env.d.ts --config assistant-worker/wrangler.jsonc --include-runtime=false` (hash: adaca622e8433cca4845856282991e04)
interface __BaseEnv_Env {
	CHAT_LIMIT: RateLimit;
	AI: Ai;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
